#!/usr/bin/env python3
"""Generate terms_map.json with Star Wars -> fictional replacements."""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from terms_expansion import EXPANSION
from terms_pass2 import PASS2

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "terms_map.json"

# Longest phrases first in JSON doesn't matter; sanitizer sorts by length.
MAP: dict[str, str] = {
    # Meta / franchise (longest first)
    "In a Future, Far, Far Away...": "In a Future, Far Beyond the Veil...",
    "In a Future, Far, Far Away": "In a Future, Far Beyond the Veil",
    "A long time ago, in a galaxy far, far away": "A long time ago, in a cluster far beyond the veil",
    "May the Force be with you": "May the Synth Flux guide you",
    "May the Craft Be with you": "May the Craft Guide You",
    "Club Penguin Star Wars Rebels Takeover": "Club Penguin Astral Rift Rebels Takeover",
    "Club Penguin Star Wars Takeover": "Club Penguin Astral Rift Takeover",
    "Untitled Star Wars Resistance Season Two episode": "Untitled Astral Rift Vanguard Season Two episode",
    "Untitled Star Wars Resistance Season Two": "Untitled Astral Rift Vanguard Season Two",
    "Untitled Star Wars film": "Untitled Astral Rift film",
    "Untitled Jabba the Hutt film": "Untitled Jabba the Magnate film",
    "Rogue One: A Star Wars Story": "Scout One: An Astral Rift Chronicle",
    "Solo: A Star Wars Story": "Solo: An Astral Rift Chronicle",
    "Star Wars: Knights of the Old Republic": "Astral Rift: Knights of the First Concord",
    "Star Wars: The Ultimate Digital Collection": "Astral Rift: The Ultimate Digital Collection",
    "Star Wars: The Ultimate Soundtrack Edition": "Astral Rift: The Ultimate Soundtrack Edition",
    "Star Wars: The Ultimate Vinyl Collection": "Astral Rift: The Ultimate Vinyl Collection",
    "Star Wars: The Comics Companion": "Astral Rift: The Comics Companion",
    "Star Wars: Battlefront II": "Astral Rift: Battlefront II",
    "Star Wars: The Mandalorian": "Astral Rift: The Veil Ranger",
    "Star Wars: Visionaries": "Astral Rift: Visionaries",
    "Star Wars: Ahsoka": "Astral Rift: Ashara",
    "The Rangers of the New Republic": "The Rangers of the New Concord",
    "Rangers of the New Republic": "Rangers of the New Concord",
    "Knights of the Old Republic": "Knights of the First Concord",
    "LEGO STAR WARS: Celebrate the Season": "LEGO ASTRAL RIFT: Celebrate the Season",
    "LEGO Star Wars": "LEGO Astral Rift",
    "Star Wars Rebels": "Astral Rift Rebels",
    "Star Wars Resistance": "Astral Rift Vanguard",
    "Star Wars Tales": "Astral Rift Tales",
    "Star Wars Insider": "Astral Rift Insider",
    "Star Wars Kids": "Astral Rift Kids",
    "Star Wars.com": "AstralRift.com",
    "StarWars.com": "AstralRift.com",
    "Friends of the Force": "Friends of the Flux",
    "Jedi Training Academy": "Lumen Training Academy",
    "Fate of the Jedi": "Fate of the Lumen",
    "The Sith Lords": "The Umbral Lords",
    "Revenge of the Sith": "Revenge of the Umbral",
    "Return of the Jedi": "Return of the Lumen",
    "The Phantom Menace": "The Veil Menace",
    "The Force Awakens": "The Flux Awakens",
    "A New Hope": "A New Dawn",
    "original trilogy": "founding trilogy",
    "prequel trilogy": "origin trilogy",
    "sequel trilogy": "successor trilogy",
    "Expanded Universe": "Extended Archive",
    "Industrial Light & Magic": "Prism Light & Magic",
    "Disney–Lucasfilm Press": "Nebula–Helix Press",
    "Lucasfilm Press": "Helix Press",
    "Lucas Licensing Ltd.": "Helix Licensing Ltd.",
    "Walt Disney Company": "Walt Nebula Company",
    "Dark Horse Comics": "Dark Comet Comics",
    "Bantha Music": "Vorn Music",
    "Bantha Tracks": "Vorn Tracks",
    "Celebration Europe II": "Convergence Europe II",
    "Droid Tales": "Automaton Tales",
    "The Galactic Gossip": "The Astral Gossip",
    "The Lost Book": "The Lost Codex",
    "The Rebel Files": "The Concord Files",
    "The Mandalorian": "The Veil Ranger",
    "The Flag Parade": "The Banner Parade",
    "Star Wars": "Astral Rift",
    "Lucasfilm": "Helix Studios",
    "LucasArts": "Helix Arts",
    "Disney+": "Nebula+",
    "Disney": "Nebula",
    "BioWare": "NovaForge",
    "Hyperspace": "Voidstream",
    "Episode VII": "Chronicle VII",
    "Episode VI": "Chronicle VI",
    "Episode IV": "Chronicle IV",
    "Episode III": "Chronicle III",
    "Episode I": "Chronicle I",
    "Visionaries": "Dreamwrights",
    "Anthology films": "Dorkeljor galulkel",
    "Storyteller": "Morgal",
    "OMEN": "VX-7206",
    "Omen": "Ionveldra",
    "Abyss": "Nisnis",
    "Ascension": "Kanisvex",
    "Celebrate the Season": "Mirdor velpra Mirjorxan",
    "Galactic Gossip": "Astral Gossip",
    "Rammahgon": "Kethmoran",
    "Razorcrest": "Veilcrest",

    # Production names (keep real names? Plan says meta terms too - anonymize franchise refs but real people can stay as they're not SW universe)
    # Actually Kathleen Kennedy etc. are tied to franchise - replace company refs only

    # Dates - specific years before generic
    "25,053 BBY": "25,053 BFC",
    "25,053BBY": "25,053BFC",
    "25,000 BBY": "25,000 BFC",
    "3956 BBY": "3956 BFC",
    "3951 BBY": "3951 BFC",
    "3640 BBY": "3640 BFC",
    "231 BBY": "231 BFC",
    "230 BBY": "230 BFC",
    "229 BBY": "229 BFC",
    "102 BBY": "102 BFC",
    "80 BBY": "80 BFC",
    "70 BBY": "70 BFC",
    "68 BBY": "68 BFC",
    "65 BBY": "65 BFC",
    "52 BBY": "52 BFC",
    "32 BBY": "32 BFC",
    "28 ABY": "28 AFC",
    "23 BBY": "23 BFC",
    "22 BBY": "22 BFC",
    "19 BBY": "19 BFC",
    "13 BBY": "13 BFC",
    "9 ABY": "9 AFC",
    "6 BBY": "6 BFC",
    "5 BBY": "5 BFC",
    "4 BBY": "4 BFC",
    "3 ABY": "3 AFC",
    "2 BBY": "2 BFC",
    "1 BBY": "1 BFC",
    "0 ABY": "0 AFC",
    "34 ABY": "34 AFC",
    "37.5 ABY": "37.5 AFC",
    "40 ABY": "40 AFC",
    "43.5 ABY": "43.5 AFC",
    "BBY": "BFC",
    "ABY": "AFC",

    # Eras & conflicts
    "First Order-Resistance War": "Prime Legion-Vanguard War",
    "Second Galactic Civil War": "Second Astral Civil War",
    "Alliance to Restore the Republic": "Alliance to Restore the Concord",
    "Galactic Civil War": "Astral Civil War",
    "High Republic Era": "High Concord Era",
    "Republic Era": "Concord Era",
    "Imperial Era": "Dominion Era",
    "Jedi Civil War": "Lumen Civil War",
    "Yuuzhan Vong War": "Yuuzhan Tide War",
    "First Battle of Geonosis": "First Battle of Kryon",
    "Battle of Geonosis": "Battle of Kryon",
    "Battle of Coruscant": "Battle of Solace Prime",
    "Battle of Nar Shaddaa": "Galmorion wengalmir Dratorwen Nisron",
    "Battle of Ebaq": "Nartorzen lyrarron Morvexsol",
    "Battle of Yavin": "Lorthal farthaldra Lyrvex",
    "Ghorman Massacre": "Ulvel Renvexgal",
    "Ghorman project": "Ionlor lormircor",
    "Operation Ringbreaker": "Veljor Ulmir",
    "Declaration of Martial Domain": "Draelzen nision Quinar Farren",
    "Boonta Eve Classic podrace": "Ulmir Belren Thalwen renvelsol",
    "Boonta Eve Classic": "Arthallor Dorionlor Kaelsol",
    "Clone Wars": "Replication Wars",
    "Cold War": "Silent War",
    "Dark Wars": "Shadow Wars",
    "Galactic War": "Astral War",
    "Expansionist Period": "Ionwenren Solniszen",
    "Old Republic": "First Concord",
    "The Old Republic": "The First Concord",

    # Force & concepts (long phrases first)
    "dark side of the Force": "shadow aspect of Synth Flux",
    "World Between Worlds": "Realm Between Realms",
    "Chain Worlds Theorem": "Chain Realms Theorem",
    "sacred Jedi texts": "sacred Lumen texts",
    "Jedi Force power": "Lumen Flux power",
    "Force technique": "Flux technique",
    "Force lightning": "Flux lightning",
    "Force power": "Flux power",
    "Force realm": "Flux realm",
    "Force shield": "Flux shield",
    "Force ghost": "Flux echo",
    "The Force": "Synth Flux",
    "Galactic Standard Calendar": "Astral Standard Calendar",
    "Standard Galactic Grid": "Standard Astral Grid",
    "Galactic Basic Standard": "Astral Basic Standard",
    "High Galactic alphabet": "High Astral alphabet",
    "Galactic Constitution": "Astral Constitution",
    "Perlemian Trade Route": "Orjor Velvel Vexlor",
    "Corellian Run": "Praron Morvel",
    "Rimma Trade Route": "Harfarthal Kavelhar Rengal",
    "Imperial calendar": "Dominion calendar",
    "Lothal Calendar": "Veldara Calendar",
    "Supreme Chancellor": "Mirzen Galvex",
    "Master of the Order": "Torquinren kavorvex kelar Praronkel",
    "Jedi Grand Master": "Lumen Grand Master",
    "Jedi High Council": "Lumen High Council",
    "Jedi youngling": "Lumen initiate",
    "Jedi Knight": "Lumen Knight",
    "Jedi Master": "Lumen Master",
    "Jedi lord": "Lumen lord",
    "Jedi Order": "Lumen Order",
    "Jedi Padawan": "Lumen Acolyte",
    "Dark Lord of the Sith": "Dark Lord of the Umbral",
    "Dark Lady of the Sith": "Dark Lady of the Umbral",
    "Sith throneworld": "Umbral throneworld",
    "Sith rebellion": "Umbral rebellion",
    "Sith assassin": "Umbral assassin",
    "Sith Chalices": "Umbral Chalices",
    "Sith Chalice": "Umbral Chalice",
    "Sith Saber": "Umbral Saber",
    "Sith Tyro": "Umbral Tyro",
    "Sith Lord": "Umbral Lord",
    "Sith Empire": "Umbral Dominion",
    "reborn Sith Empire": "reborn Umbral Dominion",
    "reconstituted Sith Empire": "reconstituted Umbral Dominion",
    "Lost Tribe of Sith": "Lost Tribe of Umbral",
    "Grand Army of the Republic": "Grand Army of the Concord",
    "Galactic Republic": "Astral Concord",
    "Galactic Empire": "Iron Dominion",
    "New Republic": "New Concord",
    "First Republic Medical Academy of Coruscant": "First Concord Medical Academy of Solace Prime",
    "Rebel Alliance Intelligence Service": "Concord Alliance Intelligence Service",
    "Rebel Alliance": "Concord Alliance",
    "Royal Naboo Security Forces": "Royal Velara Security Forces",
    "Gungan Grand Army": "Elvexlor Ionzennar Torulvex",
    "Imperial Security Bureau": "Dominion Security Bureau",
    "Imperial Navy": "Dominion Navy",
    "Imperial trooper": "Dominion trooper",
    "Imperial genocide": "Dominion genocide",
    "Confederacy of Independent Systems": "Confederacy of Independent Sectors",
    "Separatist Alliance": "Vorvexsol Elgalthal",
    "Trade Federation": "Wenron Quinquin",
    "First Order": "Prime Legion",
    "Resistance": "Vanguard",
    "the Resistance": "the Vanguard",
    "Partisans": "Freeblades",
    "Partisan": "Freeblade",
    "Nihil marauders": "Lordraul renelka",
    "Nihil": "Arcorlor",
    "Flame-Wielders": "Ember Bearers",
    "Hidden Ones": "Veiled Keepers",
    "Baran Do": "Lyrpraren Pralor",
    "Hutt Cartel": "Magnate Cartel",
    "Heltraxi": "Pranar",
    "Scarlet Skulls": "Narul Wenvor",
    "Core Founders": "Moriongal Wenmorgal",
    "Office of the Chancellor": "Ulgal arion prakelnar Zenyor",
    "Marshal of the New Republic": "Marshal of the New Concord",
    "Clone trooper": "Replica trooper",
    "clone trooper": "replica trooper",
    "clone commando": "replica commando",
    "stormtroopers": "dominion troopers",
    "stormtrooper": "dominion trooper",
    "Separatist": "Morpraxan",
    "Confederate": "Torcorcor",
    "Confederacy": "Solnis",
    "Imperial": "Dominion",
    "Republic": "Concord",
    "Empire": "Dominion",
    "Jedi": "Lumen",
    "Sith": "Umbral",
    "Padawan": "Acolyte",
    "Mandalorian": "Veil Ranger",
    "foundling": "renmor",
    "Force": "Flux",
    "Mortis gods": "Mornis gods",

    # Characters (longest / full names first)
    "Marshal of the New Republic Cara Dune": "Marshal of the New Concord Kara Dunel",
    "Darth Sidious' Sith Chalice": "Lord Malvek's Umbral Chalice",
    "Supreme Chancellor of the Galactic Republic": "Supreme Chancellor of the Astral Concord",
    "Senator Padmé Amidala": "Senator Padma Amidala",
    "Queen Padmé Amidala": "Queen Padma Amidala",
    "Padmé Amidala": "Padma Amidala",
    "Sheev Palpatine": "Shev Paltrine",
    "Emperor Palpatine": "Emperor Paltrine",
    "Darth Sidious": "Lord Malvek",
    "Darth Caedus": "Lord Caedus",
    "Darth Nihilus": "Lord Nihilus",
    "Obi-Wan Kenobi": "Oban Krennan",
    "Qui-Gon Jinn": "Quin Gor Jinn",
    "Luke Skywalker": "Luken Skyvale",
    "Ben Skywalker": "Ben Skyvale",
    "Jacen Solo": "Jace Solen",
    "Han Solo": "Han Solen",
    "Asajj Ventress": "Narnarar Ionelsar",
    "General Grievous": "Yorwenwen Artor",
    "Mon Mothma": "Vexcor Morron",
    "Cassian Andor": "Quinarel Draron",
    "Jyn Erso": "Jorka Torlorhar",
    "Saw Gerrera": "Prator Zensol",
    "Luthen Rael": "Torvordor Torthal",
    "Orson Krennic": "Elkelnar Ronsolnar",
    "Ezra Bridger": "Vorjor Velulnis",
    "Ahsoka Tano": "Ashara Tano",
    "Din Djarin": "Lorsolul Dorcor",
    "Cara Dune": "Kara Dunel",
    "Gina Carano": "Harkacor Farlyrfar",
    "Dave Filoni": "Jornis Dradra",
    "Jon Favreau": "Mirdor Ulel",
    "Kathleen Kennedy": "Rendor Vextor",
    "Bob Iger": "Nisarion Mirjor",
    "Caitlin Kennedy": "Vorsarjor Galjor",
    "Brian Kesinger": "Narkel Belul",
    "Anthony Daniels": "Renarlor Eldra",
    "Ed Asner": "Yordra Ororthal",
    "Eddie Asner": "Nislor Eljorren",
    "Edward Asner": "Kelcor Morka",
    "Master Yoda": "Dorlor Thalxannar",
    "Yoda": "Pralorren",
    "Palpatine": "Paltrine",
    "Skywalker": "Skyvale",
    "Kenobi": "Krennan",
    "Amidala": "Solthalsol",
    "Dooku": "Belnar",
    "Ventress": "Jorkel",
    "Grievous": "Narsar",
    "Revan": "Yorlyrvor",
    "Meetra Surik": "Coror Ornar",
    "Carth Onasi": "Corthalmor Faryorul",
    "Admiral Carth Onasi": "Kelcortor Thalnisar Lyrvorzen",
    "Hero of Tython": "Farvexxan galvelron Harquinlor",
    "Vrook Lamar": "Dratorfar Velmorgal",
    "Vergere": "Lyrsolnar",
    "Lumiya": "Galyorren",
    "Vestara Khai": "Iondorul Oryor",
    "Gavar Khai": "Veldraka Dortor",
    "Charsae Saal": "Elkel Pravexel",
    "Koro Ziil": "Velvexhar Fardrador",
    "Tila Mong": "Draor Kael",
    "Tokra Hazz": "Velnisor Nisyormor",
    "Lene Kostana": "Renor Jornis",
    "Rael Averross": "Yorhar Lorwenfar",
    "Crucitorn": "Thalcorron",
    "Jenza": "Arzen",
    "Duja": "Lyrgal",
    "Sabé": "Sabe",
    "Saché": "Sache",
    "Rabé": "Rabe",
    "Yané": "Yane",
    "Quarsh Panaka": "Lorbeltor Dortor",
    "Mariek Panaka": "Vexel Harhar",
    "Fassio Ablund": "Torjorel Ronvorvor",
    "Hanrai": "Kavel",
    "Yuehiro": "Xanron",
    "Master Numoda": "Narormir Quinor",
    "Masamu": "Vexorvex",
    "Ram Jomaram": "Farvex Draka",
    "Vark Tarpalin": "Mornar Lorarmir",
    "Zyle Keem": "Lyryorvor Pramor",
    "Gavi": "Wenren",
    "Ax Tagrin": "Harzenvel Zenarjor",
    "Kazuda Xiono": "Prahar Dornis",
    "Imanuel Doza": "Gallor Morgalel",
    "Tamara Ryvora": "Sarvex Velcor",
    "Synara San": "Drahar Orul",
    "Everi Chalis": "Hargalvel Veljorel",
    "Hazram Namir": "Lyrfar Morsol",
    "Roach": "Vextor",
    "Boss": "Yorpraor",
    "Trooper 17": "Tordrasar 17",
    "Clone trooper 17": "Replica trooper 17",
    "Three-Five": "Mirsol-Mirwen",
    "Jango Fett": "Vexel Kelsarsol",
    "Jabba the Hutt": "Jabba the Magnate",
    "Jabba": "Solren",
    "Grogu": "Belhar",
    "The Child": "Thalmor Corgal",
    "Rey": "Tormor",
    "BB-8": "BX-8",
    "C-3PO": "C-3PX",
    "R2-D2": "R2-K4",
    "T3-M4": "VX-3615",
    "3C-FD": "VX-4600",
    "SM-33": "VX-8A49",
    "Tuut Orial": "Dracor Narthal",
    "KB": "VX-5928",
    "Fern": "Praronthal",
    "Wim": "Zengal",
    "Neel": "Narsar",
    "Vane": "Dornisar",
    "Otalp": "Renjor",
    "Remoh": "Vorfarsar",
    "Morpitoo": "Morpivan",
    "The Morpitoo": "Thalcor Ronbel",
    "Duke Solha": "Corquinwen Morfarfar",
    "Doc": "Praquin",
    "Archiban Kimble": "Harvel Kelron",
    "Suudaa Nem'ro": "Suudaa Nemro",
    "Nem'ro": "Nemro",
    "Kaliyo Djannis": "Jorbel Morvorvel",
    "Skadge": "Nisthalion",
    "Mika Dorin": "Harharlyr Arkel",
    "Kebla Yurt": "Harsol Sardor",
    "Ziagrom": "Prahar",
    "Idryssa Barrack": "Zenthalyor Ultorar",
    "Vel Sartha": "Ronquin Jorren",
    "Syril Karn": "Mirka Xanzen",
    "Linus Mosk": "Farjor Vexvex",
    "Willi": "Morbel",
    "Dedra Meero": "Narulel Vorlyr",
    "Major Lio Partagaz": "Sarmorgal Galnar Pravorxan",
    "Hendri Underholt": "Niswen Wenor",
    "Missus Parse": "Uldor Dorxan",
    "Combo": "Ronardra",
    "Burra": "Vordrajor",
    "Ithia": "Lyrprabel",
    "Ahri Raas": "Yorarvel Nisvel",
    "Tikk": "Kafarxan",
    "General Crix Madine": "Veltorel Sartorbel Tororlor",

    # Places (longest first)
    "Inner Rim Territories": "Torhar Vorfarar Drawenren",
    "Outer Rim Territories": "Kaka Dorcorron Morul",
    "Black Spire Outpost": "Narsolsar Dorhar Galsar",
    "Peragus Mining Facility": "Zenfar Wenwensar Torronnis",
    "Theed Royal Palace": "Lorkelion Jorsol Yorvexren",
    "Senate Office Building": "Xanwen Lornis Belmirvex",
    "Chancellor's Suite": "Yorlorzen Mirjornar",
    "Lothal Jedi Temple": "Veldara Lumen Temple",
    "Naval Station Validusia": "Velsolquin Ularka Sarthalqui",
    "First Republic Medical Academy of Coruscant": "First Concord Medical Academy of Solace Prime",
    "Nem'ro's Palace": "Nemro's Palace",
    "Cliffs of Theed": "Ronmirgal jorulmor Orbelgal",
    "Temple Island": "Galsolron Narwen",
    "Echo Base": "Morlyr Sarlyrtor",
    "Ferrix City": "Harkaor Belnar",
    "Ferrix Terminal": "Ronsarkel Mirtorsol",
    "Jedha City": "Elren Nisyorvex",
    "Tythoni Square": "Zenlorgal Xanquinzen",
    "Palmo Plaza": "Yorhar Corpracor",
    "Maltheen Divide": "Wenion Nishar",
    "Lonisa City": "Eltor Lorzenpra",
    "Lake Lonisa": "Belkafar Drayoryor",
    "Farodin Woods": "Drahar Mirhar",
    "Coronet City": "Arnar Ronka",
    "Mos Eisley": "Vornar Arquin",
    "Mos Espa": "Jorquin Vexwenion",
    "Toryaz Station": "Zenthal Correnor",
    "Nar Shaddaa": "Wenharlyr Mirwen",
    "Cato Neimoidia": "Kapraka Harulvel",
    "Engai system": "Ronquin kelor",
    "Kuliquo belt": "Orkelfar nisquinlor",
    "Kuliquo system": "Prathal galdordor",
    "Validusia system": "Lorpra dorbel",
    "Mayagil sector": "Torlyrbel sarcorvor",
    "Stratos Distribution": "Lyrrenhar Prapra",
    "Port Borgo": "Zenwenfar Uljorlyr",
    "Ringali Shell": "Xanion Zenel",
    "Core Worlds": "Sarpra Mornis",
    "Inner Rim": "Corlyr Narlor",
    "Outer Rim": "Nissol Thaljorion",
    "Mid Rim": "Belvex Torormir",
    "Coruscant": "Solace Prime",
    "Naboo": "Velara",
    "Theed": "Torfarzen",
    "Mustafar": "Vexxanor",
    "Geonosis": "Kryon",
    "Kamino": "Elar",
    "Batuu": "Galthal",
    "Mokivj": "Draar",
    "Jedha": "Lyrion",
    "Ghorman": "Vexorvex",
    "Eadu": "Quincor",
    "Dorin": "Harvexlor",
    "Dor'shan": "Lyrpraion",
    "Kesh": "Narjorbel",
    "Tahv": "Dorel",
    "Valo": "Wenvelsar",
    "Bonadan": "Vexvexgal",
    "Taris": "Morquin",
    "Korriban": "Corvor",
    "Peragus": "Jorion",
    "Telos IV": "Dravoryor Vordra",
    "Clak'dor VII": "Lorulgal Drathal",
    "Lothal": "Veldara",
    "Ahch-To": "Lyrjorquin-Draquin",
    "Exegol": "Zensol",
    "Hoth": "Frosthold",
    "Ferrix": "Kayorar",
    "Nal Hutta": "Lyrronsol Vexharka",
    "Watoru": "Kacor",
    "Rhinnal": "Prayorlyr",
    "Neimoidia": "Zenkelwen",
    "Tatooine": "Sandreach",
    "Corellia": "Galron",
    "Lorrd": "Rontorlor",
    "Kuat": "Sarwenkel",
    "Ebaq 9": "Pravexthal 9",
    "Ebaq": "Quinlyr",
    "Dreshdae": "Vexren",
    "Upper City": "Mirxanlor Ulquin",
    "Malachor": "Belzenron",
    "Citadel Station": "Narlorron Pralor",
    "Station 2LC/Blue": "Solren 2Sarlor/Jordordra",

    # Technology / ships
    "Bavos-II heavy-duty military space platform": "Yorzenka-Lyrul harel-harnaryor dradorwen narwenvel solhar",
    "Bavos-I heavy-duty military space platform": "Lyrka-Nistor morlyrtor-xanion dratorul xanrensol xanzen",
    "TX-225 GAVw \"Occupier\" combat assault tank": "Sarjor-225 Iontor \"Vexmirsar\" orrensol dorlyrpra praquindra",
    "Phase I clone trooper armor": "Phase I replica trooper armor",
    "clone trooper armor": "replica trooper armor",
    "Bonadan alloy heavy suit": "Kalorlyr prawenul harorzen zenrensar",
    "Bonadan-alloy armor": "Morzen-jormortor corsar",
    "3C-series utility droid": "3C-series utility automaton",
    "T3-series utility droid": "T3-series utility automaton",
    "HK-50 series assassin droid": "HK-50 series assassin automaton",
    "flying attack droids": "flying attack automatons",
    "flying attack droid": "flying attack automaton",
    "incubation droid": "incubation automaton",
    "staircase droid": "staircase automaton",
    "protocol droid": "protocol automaton",
    "astromech droid": "astromech automaton",
    "utility droid": "utility automaton",
    "assassin droid": "assassin automaton",
    "B1-Series battle droids": "B1-Series battle automatons",
    "B1-Series battle droid": "B1-Series battle automaton",
    "Death Star superweapon": "Void Core superweapon",
    "Death Star": "Void Core",
    "Millennium Falcon": "Eclipse Runner",
    "Star Destroyers": "Void Destroyers",
    "TIE/LN starfighters": "Void/LN starfighters",
    "RZ-1 A-wing interceptors": "Mirorkel-1 Rensol-wentorgal harlyr",
    "RZ-1 A-wing interceptor": "Harlorpra-1 Vexcor-farmir loryorren",
    "YT-1300 light freighter": "Belwen-1300 harxan mirka",
    "Altor-class supply ship": "Kelel-kael narronkel thalsol",
    "_Altor_-class supply ship": "_Mirsolsol_-corulka corsolar narvex",
    "Defender-class light corvette": "Vordor-mirarquin orlor galronor",
    "_Defender_-class light coroutine": "_Ulnar_-ionvexkel xanmorzen harul",
    "Interdictor-class cruiser": "Elquin-lorelul harzen",
    "_Interdictor_-class cruiser": "_Eldra_-eltor arjor",
    "_Leviathan_": "_Vorcoryor_",
    "Ebon Hawk": "Tordornar Orgalion",
    "_Ebon Hawk_": "_Tordornar Orgalion_",
    "Harbinger": "Sarvor",
    "_Harbinger_": "_Sarvor_",
    "King's Ransom": "Kelsolfar Xankelren",
    "_King's Ransom_": "_Kelsolfar Xankelren_",
    "Razor Crest": "Veil Crest",
    "_Razor Crest_": "_Veil Crest_",
    "Possibility": "Mirnaryor",
    "_Possibility_": "_Mirnaryor_",
    "Pikka's Pride": "Dorxan Narlor",
    "_Pikka's Pride_": "_Dorxan Narlor_",
    "Colossus": "Ionul",
    "_Colossus_": "_Ionul_",
    "Innovator": "Solpra",
    "_Innovator_": "_Solpra_",
    "HFY-3920 shuttle ferry": "Lorgalron-3920 vexrenka elmircor",
    "Fondor Haulcraft": "Yorcor Pramor",
    "Nomad Four transport": "Elnisvor Mirsarhar arthal",
    "88-R Nightscreamer": "88-Lorel Galcor",
    "88-R \"Nightscreamer\"": "88-Corkasol \"Orionnis\"",
    "A95 Stingbeam": "Zendrathal95 Farlorsar",
    "Beemon package": "Veymon package",
    "auxiliary brain": "auxiliary cortex",
    "berserker rifle": "ravager rifle",
    "Galven-pattern barrel": "Draor-farnis dramor",
    "kyber crystals": "flux crystals",
    "lightsaber": "flux blade",
    "blaster bolts": "pulse bolts",
    "blaster rifle": "pulse rifle",
    "blaster": "pulse weapon",
    "DC-15S": "VX-9013",
    "turbolaser cannons": "galul sartor",
    "anti-starfighter turbolasers": "thalyor-drahar solulthal",
    "concussion missile bank": "niselvex renlyr xanoryor",
    "deflector shield generator": "draelren solnar jorquin",
    "deflector shields": "quinwensar ulthal",
    "repulsorcraft": "oryor",
    "speeder bike": "belionron vexbelel",
    "shuttle ferry": "mirkator wenyorvor",
    "beckon call": "summon ping",
    "uvak": "uvax",
    "wampa": "frost beast",
    "bacta": "medigel",
    "droid": "automaton",
    "droids": "automatons",

    # Organizations / companies
    "Damask Holdings": "Corthalren Velkazen",
    "Beemon Laboratories": "Ronronnar Wenzen",
    "Duwani Mechanical Products": "Sarren Vexmor Thalnissar",
    "Czerka Arms": "Elbelnar Morquin",
    "Kuat Drive Yards": "Solquinka Nisbel Nismirfar",
    "Rendili StarDrive": "Sarjor Farthal",
    "Ferrix Field Yards": "Prasarcor Velnar Vorharfar",
    "Ferrix Entry Ferry Service": "Hartor Arbellor Mirion Yorharxan",
    "Outer Rim Construction and Assembly": "Galarar Yorzen Narorion morcoryor Elmor",
    "Plasma Energy Engineering": "Quinthalmo Harlor Corvexren",
    "Pre-Mor Enforcement": "Farionka-Dorsarsol Vorel",
    "61st Mobile Infantry": "61thalrendra Nisul Solzenor",
    "Journal of Xenomedicine": "Kalyrvor ulmirar Yormor",

    # Species
    "Kaminoan": "Belyor",
    "Kel Dor": "Tornarquin Narel",
    "Twi'lek": "Dorwenron",
    "Gungan": "Kaul",
    "Keshiri": "Ormoror",
    "Rattataki": "Yorjorsol",
    "Iktotchi": "Ronmorthal",
    "Mirialan": "Belgalel",
    "Aqualish": "Ionmir",
    "Bonbrak": "Quinxanor",
    "Valons": "Valeans",
    "Aalagar": "Elvorvex",
    "Bith": "Sararnis",
    "Duros": "Jormirka",
    "Houk": "Dorren",
    "Rodian": "Saryor",
    "Squidge": "Squill",
    "Hutt": "Magnate",
    "Huttese": "Magnate tongue",

    # Misc in-universe
    "Aurebesh": "Narsoltor",
    "Bazeese script": "Thalvor jorcorbel",
    "sabacc": "savaq",
    "credits": "trade chits",
    "podrace": "skyrace",
    "Tapas": "Heatbind",
    "Endure": "Painward",
    "imprint": "bondmark",
    "dying ceremony": "veil ceremony",
    "farewell ceremony": "parting rite",
    "Kalkite": "Velkrite",
    "Acthorn tree": "Tarnwood tree",
    "Snowflake Snack": "Crystal Treat",
    "Full Monty Catering": "Full Course Catering",
    "Morpitoo's language": "Morpivan's language",
    "Hanrai's library seal": "Hanar's archive seal",
    "Dujas brooch": "Duja's brooch",
    "Duja's brooch": "Dura's brooch",
    "Sith meditation incense burner": "Umbral meditation incense burner",
    "ancient Sith": "ancient Umbral",
    "Sith culture": "Umbral culture",
    "Sith artifact": "Umbral artifact",
    "Sith artifacts": "Umbral artifacts",
    "Sith origins": "Umbral origins",
    "Sith identity": "Umbral identity",
    "Sith tendencies": "Umbral tendencies",
    "Sith Lord": "Umbral Lord",
    "ties to the Sith": "ties to the Umbral",
    "viewable by Jedi": "viewable by Lumen",
    "fall to the dark side": "fall to the shadow aspect",
    "fall to the dark side of the Force": "fall to the shadow aspect of Synth Flux",
    "dark side": "shadow aspect",
    "presence in the Force": "presence in Synth Flux",
    "one with the Force": "one with Synth Flux",
    "through the Force": "through Synth Flux",
    "in the Force": "in Synth Flux",
    "hide their presence in the Force": "hide their presence in Synth Flux",
    "opened the platform's base with the Force": "opened the platform's base with Synth Flux",
    "Force-based": "Flux-based",
    "Force-based organization": "Flux-based organization",
    "Force-based order": "Flux-based order",
    "C.R.C.": "N.R.C.",
    "BFE": "BVE",
    "LY": "CY",
    "ISB": "DSB",
    "Droid Tales": "Automaton Tales",
    "BB-8 and the Snow Monster": "BX-8 and the Snow Monster",
    "_BB-8 and the Snow Monster_": "_BX-8 and the Snow Monster_",
    "_Droid Tales_": "_Automaton Tales_",
    "_Star Wars_": "_Astral Rift_",
    "Star Wars:": "Astral Rift:",
    "Star Wars universe": "Astral Rift universe",
    "_Star Wars_ universe": "_Astral Rift_ universe",
    "LEGO _Star Wars_": "LEGO _Astral Rift_",
    "Return of the Jedi": "Return of the Lumen",
    "Revenge of the Sith": "Revenge of the Umbral",
    "Galactic Empire's": "Iron Dominion's",
    "Galactic Republic's": "Astral Concord's",
    "Galactic Senate": "Astral Senate",
    "Luke Skywalker": "Luken Skyvale",
    "Skywalkers": "Skyvales",
    "Luke": "Luken",
    "Palpatine": "Paltrine",
    "Naboo's": "Velara's",
    "Naboo": "Velara",
    "Tatooine's": "Sandreach's",
    "Tatooine": "Sandreach",
    "Jabba The Magnate": "Melko the Magnate",
    "Jabba the Magnate": "Melko the Magnate",
    "Jabba the Hutt": "Melko the Magnate",
    "Jabba-centric": "Melko-centric",
    "Jabba": "Melko",
    "Nal Hutta": "Nal Magnara",
    "Hutt's": "Magnate's",
    "the Hutt": "the Magnate",
    "Darth Caedus": "Lord Caedus",
    "Darth Nihilus": "Lord Nihilus",
    "Umbral Lord Darth Caedus": "Umbral Lord Caedus",
    "Umbral Lord Lord Caedus": "Umbral Lord Caedus",
    "Umbral Lord Lord Malvek": "Umbral Lord Malvek",
    "Sidious'": "Malvek's",
    "Sidious": "Malvek",
    "Force-sensitive": "Flux-sensitive",
    "clone troopers": "replica troopers",
    "clone trooper": "replica trooper",
    "clone commando": "replica commando",
    "clone of": "replica of",
    "surviving clone": "surviving replica",
    "other clone": "other replica",
    "other clones": "other replicas",
    "surviving clones": "surviving replicas",
    "many clones": "many replicas",
    "clones": "replicas",
    "Jacen": "Jace",
    "Dark Lord Of The Umbral's's": "Dark Lord Of The Umbral's",
    "Astral Concord's's": "Astral Concord's",
    "Iron Dominion's's": "Iron Dominion's",
    "Velara's's": "Velara's",
    "Sandreach's's": "Sandreach's",
    "Sith-infiltrated": "Umbral-infiltrated",
    "Knight-turned-Sith Lord": "Knight-turned-Umbral Lord",
    "-Sith": "-Umbral",
    "turned-Sith Lord": "turned-Umbral Lord",
    "turned-Sith": "turned-Umbral",
    "Dark Lord of the Sith's": "Dark Lord of the Umbral's",
    "Dark Lord of the Sith": "Dark Lord of the Umbral",
    "Sith Lord": "Umbral Lord",
    "Yoda": "Zephara",
    "Jacen Solo": "Jace Solen",
    "Imperials": "Dominion forces",
    "ex-Imperial": "ex-Dominion",
    "Imperial": "Dominion",
    "Droid": "Automaton",
    "Rogue One: A Astral Rift Story": "Rogue One: An Astral Rift Chronicle",
    "Solo: A Astral Rift Story": "Solo: An Astral Rift Chronicle",
    "Untitled Jabba The Magnate Film": "Untitled Melko The Magnate Film",
    "Untitled Jabba the Magnate film": "Untitled Melko the Magnate film",
}

MAP.update(EXPANSION)
MAP.update(PASS2)

noops = sorted(source for source, target in MAP.items() if source == target)
if noops:
    raise ValueError(
        "No-op mappings are not allowed in terms_map dictionaries: "
        + ", ".join(noops[:20])
    )

OUT.write_text(json.dumps(MAP, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
print(f"Wrote {len(MAP)} mappings to {OUT}")
