"""Additional Star Wars -> Astral Rift replacements for pass 2."""

EXPANSION: dict[str, str] = {
    # Regions
    "Outer Rim Territories": "Fringe Expanse Territories",
    "Outer Rim Construction and Assembly": "Fringe Expanse Construction and Assembly",
    "Outer Rim": "Fringe Expanse",
    "Inner Rim Territories": "Inner Veil Territories",
    "Inner Rim": "Inner Veil",
    "Mid Rim": "Mid Veil",
    "Core Worlds'": "Core Nexus'",
    "Core Worlds": "Core Nexus",
    "Core Founders": "Nexus Founders",
    "Mayagil sector": "Maygar sector",
    "Ringali Shell": "Ringvale Shell",
    "Rimma Trade Route": "Rimvale Trade Route",
    "Perlemian Trade Route": "Perlemian Corridor",
    "Corellian Run": "Corvel Run",
    "Expansionist Period": "Pioneer Era",

    # Planets & places
    "Bonadan alloy heavy suit": "Korrath alloy heavy suit",
    "Bonadan-alloy armor": "Korrath-alloy armor",
    "Bonadan-alloy": "Korrath-alloy",
    "Bonadan alloy": "Korrath alloy",
    "Bonadan": "Korrath",
    "Peragus Mining Facility": "Peragos Mining Facility",
    "Peragus": "Peragos",
    "Korriban": "Morvath",
    "Malachor": "Vexmor",
    "Taris": "Orilan",
    "Telos IV": "Telmar IV",
    "Kamino": "Genos Prime",
    "Mustafar": "Ashavar",
    "Nar Shaddaa": "Nar Shaden",
    "Ferrix Terminal": "Ferrin Terminal",
    "Ferrix City": "Ferrin City",
    "Ferrix Field Yards": "Ferrin Field Yards",
    "Ferrix Entry Ferry Service": "Ferrin Entry Ferry Service",
    "Ferrixian": "Ferrinian",
    "Ferrix": "Ferrin",
    "Corellia": "Corvel",
    "Coronet City": "Coronet Bay",
    "Jedha City": "Jedren City",
    "Jedha": "Jedren",
    "Clak'dor VII": "Clakdor VII",
    "Rhinnal": "Rhinvale",
    "Neimoidia": "Neimord",
    "Cato Neimoidia": "Cato Neimord",
    "Valo": "Valeo",
    "Dorin'shan": "Dorval'shan",
    "Dor'shan": "Dorval'shan",
    "Dorin": "Dorval",
    "located on Dorlen—": "located on Dorval—",
    "traveled to Dorlen to": "traveled to Dorval to",
    "Dorlen'shan": "Dorval'shan",
    "planet Dorlen": "planet Dorval",
    "Dorlen's helium": "Dorval's helium",
    "Kesh": "Keshara",
    "Tahv": "Tahven",
    "Lorrd": "Lorren",
    "Dreshdae": "Dreshden",
    "Exegol": "Exilon",
    "Batuu": "Bathen",
    "Black Spire Outpost": "Spire Market",
    "Black Spire Station": "Spire Market",
    "Mokivj": "Mokiven",
    "Eadu": "Eadan",
    "Ghorman Massacre": "Ghoran Massacre",
    "Ghorman project": "Ghoran project",
    "Ghormans": "Ghorans",
    "Ghorman": "Ghoran",
    "Watoru": "Watora",
    "Ahch-To": "Ahchlen",
    "Temple Island": "Sanctum Island",
    "Theed Royal Palace": "Theeden Royal Palace",
    "Theed Hangar": "Theeden Hangar",
    "Theed": "Theeden",
    "Mos Espa": "Mos Espan",
    "Mos Eisley": "Mos Eisden",
    "Echo Base": "Echo Outpost",
    "The Drunk Side": "The Murk Side",
    "Upper City": "Upper District",
    "Equipment Emporium": "Equipment Exchange",
    "Chancellor's Suite": "Chancellor's Quarters",
    "Senate Office Building": "Senate Annex",
    "Citadel Station": "Citadel Platform",
    "Naval Station Validusia": "Naval Station Validara",
    "Validusia system": "Validara system",
    "Port Borgo": "Port Borga",
    "Kuliquo system": "Prathal galdordor",
    "Kuliquo belt": "Orkelfar nisquinlor",
    "Engai system": "Engara system",
    "Lonisa City": "Lonisa Bay",
    "Lake Lonisa": "Belkafar Drayoryor",
    "Farodin Woods": "Drahar Mirhar",
    "Palmo Plaza": "Palmo Square",
    "Maltheen Divide": "Maltheen Rift",
    "Tythoni Square": "Tythoni Plaza",
    "Toryaz Station": "Toryaz Hub",
    "Stratos Distribution": "Stratos Network",
    "Nemro's Palace": "Nemro's Estate",
    "Nal Magnara": "Nal Marava",
    "Yavin": "Prism Vale",
    "Battle of Yavin": "Battle of Prism Vale",
    "Battle of Nar Shaddaa": "Battle of Nar Shaden",
    "Boonta Eve Classic podrace": "Bonta Eve Classic podrace",
    "Boonta Eve Classic": "Bonta Eve Classic",

    # Species
    "craniopods": "cranopods",
    "Y'bith": "Y'brith",
    "Bith": "Brith",
    "Rodian": "Rodan",
    "Twi'lek": "Sylari",
    "Gungan": "Grelon",
    "Gungan Grand Army": "Grelon Grand Army",
    "Duros": "Duran",
    "Kaminoan": "Genosian",
    "Kel Dor": "Keldoran",
    "Rattataki": "Rattaki",
    "Iktotchi": "Iktochi",
    "Mirialan": "Miriallan",
    "Aqualish": "Aquan",
    "Houk": "Houkan",
    "Keshiri": "Kesharan",
    "Bonbrak": "Quinxanor",
    "Valons": "Valeans",
    "Squidge": "Squill",
    "Morpitoo": "Morpivan",
    "uvak": "uvax",

    # Factions & military
    "Confederacy Of Independent Sectors": "League Of Independent Sectors",
    "Confederacy of Independent Systems": "League of Independent Sectors",
    "Confederacy": "League",
    "Confederate": "League",
    "Separatist": "Secessionist",
    "Trade Federation": "Commerce League",
    "Gungan Grand Army": "Grelon Grand Army",
    "Alliance To Restore The Concord": "Ionsarmir Galkagal Farvexdor Thalcor Yorlyr",
    "Grand Army Of The Concord": "Quinren Sarthaljor Niswen Mirdraion Yordorkel",

    # Characters - KOTOR & major
    "Dark Lord Of The Umbral Revan": "Dark Lord Of The Umbral Kaelen",
    "Dark Lord Of The Umbral Lord Nihilus": "Dark Lord Of The Umbral Lord Nilvar",
    "Lord Nihilus": "Lord Nilvar",
    "Meetra Surik": "Meetra Valis",
    "Carth Onasi": "Carth Orlen",
    "Revan": "Kaelen",
    "Mika Doran": "Mika Dorlen",
    "stock Doran": "stock Dorlen",
    "Doran sent": "Dorlen sent",
    "that Doran was": "that Dorlen was",
    "Assumption ends here.": "",
    "Kebla Yurt": "Kebla Vorn",
    "Ziagrom": "Ziarom",
    "Lumiya": "Vexara",
    "Dooku": "Count Dural",
    "Quin Gor Jinn": "Farel Tordra Velron",
    "Crucitorn": "Thalcorron",
    "Vrook Lamar": "Dratorfar Velmorgal",
    "Vergere": "Lyrsolnar",
    "Hero of Tython": "Farvexxan galvelron Harquinlor",
    "Archiban Kimble": "Harvel Kelron",
    "Doc": "Praquin",
    "Skadge": "Nisthalion",
    "Kaliyo Djannis": "Jorbel Morvorvel",
    "Vestara Khai": "Iondorul Oryor",
    "Gavar Khai": "Veldraka Dortor",
    "Charsae Saal": "Elkel Pravexel",
    "Koro Ziil": "Velvexhar Fardrador",
    "Tila Mong": "Draor Kael",
    "Tokra Hazz": "Velnisor Nisyormor",
    "Lene Kostana": "Renor Jornis",
    "Rael Averross": "Yorhar Lorwenfar",
    "Jango Fett": "Jango Vett",
    "Asajj Ventress": "Asajj Ventra",
    "General Grievous": "General Krevox",
    "Cassian Andor": "Cassian Endor",
    "Mon Mothma": "Mon Vothra",
    "Saw Gerrera": "Saw Gerron",
    "Orson Krennic": "Orson Kreval",
    "Ezra Bridger": "Ezra Bridven",
    "Jyn Erso": "Jyn Erson",
    "Luthen Rael": "Torvordor Torthal",
    "Grogu": "Grovo",
    "Din Djarin": "Din Jarros",
    "The Child": "The Foundling",
    "Cara Dune": "Kara Dunel",
    "Ashara Tano": "Kalor Arion",
    "Ahsoka Tano": "Ashara Tano",
    "Ram Jomaram": "Farvex Draka",
    "Vark Tarpalin": "Mornar Lorarmir",
    "Zyle Keem": "Lyryorvor Pramor",
    "Everi Chalis": "Hargalvel Veljorel",
    "Hazram Namir": "Lyrfar Morsol",
    "Boss": "Yorpraor",
    "Fassio Ablund": "Torjorel Ronvorvor",
    "Duja": "Lyrgal",
    "Padma Amidala": "Jorel Quinwenar",
    "Amidala": "Solthalsol",
    "Quarsh Panaka": "Lorbeltor Dortor",
    "Mariek Panaka": "Vexel Harhar",
    "Rabe": "Lyrel",
    "Sabe": "Vexkahar",
    "Sache": "Narcor",
    "Yane": "Farorar",
    "Jenza": "Arzen",
    "Heilan Rotham": "Prathal Zenyor",
    "Vel Sartha": "Ronquin Jorren",
    "Syril Karn": "Mirka Xanzen",
    "Linus Mosk": "Farjor Vexvex",
    "Willi": "Morbel",
    "Hanrai": "Kavel",
    "Yuehiro": "Xanron",
    "Master Numoda": "Narormir Quinor",
    "Masamu": "Vexorvex",
    "Ax Tagrin": "Harzenvel Zenarjor",
    "Kazuda Xiono": "Prahar Dornis",
    "Imanuel Doza": "Gallor Morgalel",
    "Tamara Ryvora": "Sarvex Velcor",
    "Synara San": "Drahar Orul",
    "Duke Solha": "Corquinwen Morfarfar",
    "Burra": "Vordrajor",
    "Ithia": "Lyrprabel",
    "Ahri Raas": "Yorarvel Nisvel",
    "Tikk": "Kafarxan",
    "Otalp": "Renjor",
    "Remoh": "Vorfarsar",
    "Roach": "Vextor",
    "Three-Five": "Mirsol-Mirwen",
    "Combo": "Ronardra",
    "Vaz Traniff": "Ronthal Draprasar",
    "Fern": "Praronthal",
    "Wim": "Zengal",
    "Neel": "Narsar",
    "Vane": "Dornisar",
    "Tuut Orial": "Dracor Narthal",
    "KB": "VX-5928",
    "Gavi": "Wenren",
    "Rey": "Tormor",
    "Hendri Underholt": "Niswen Wenor",
    "Missus Parse": "Uldor Dorxan",
    "General Crix Madine": "Veltorel Sartorbel Tororlor",
    "Idryssa Barrack": "Zenthalyor Ultorar",
    "Dedra Meero": "Narulel Vorlyr",
    "Major Lio Partagaz": "Sarmorgal Galnar Pravorxan",

    # Ships & manufacturers
    "_Ebon Hawk_": "_Obsidian Talon_",
    "Ebon Hawk": "Obsidian Talon",
    "_Harbinger_": "_Warden_",
    "Harbinger": "Warden",
    "_Leviathan_": "_Vorcoryor_",
    "Leviathan": "Vorcoryor",
    "_Interdictor_": "_Barrier_",
    "Interdictor-class cruiser": "Barrier-class cruiser",
    "Interdictor": "Barrier",
    "_King's Ransom_": "_Kelsolfar Xankelren_",
    "_Innovator_": "_Solpra_",
    "_Colossus_": "_Ionul_",
    "_Possibility_": "_Mirnaryor_",
    "_Veil Crest_": "_Drabel Lyrtor_",
    "_Pikka's Pride_": "_Dorxan Narlor_",
    "YT-1300": "XT-1300",
    "Kuat Drive Yards": "Krev Drive Yards",
    "Rendili StarDrive": "Rendali StarDrive",
    "Czerka Arms": "Czeran Arms",
    "Duwani Mechanical Products": "Sarren Vexmor Thalnissar",
    "Damask Holdings": "Corthalren Velkazen",
    "Beemon Laboratories": "Ronronnar Wenzen",
    "Beemon": "Praion",
    "Plasma Energy Engineering": "Quinthalmo Harlor Corvexren",
    "Pre-Mor Enforcement": "Farionka-Dorsarsol Vorel",
    "Ikas-Adno": "Solren-Corarron",
    "Fondor Haulcraft": "Yorcor Pramor",
    "DC-15S": "DX-15S",
    "Void/LN starfighters": "Quinion/Orhar rennisar",
    "Void/LN Starfighters": "Lorfar/Kajorvor Velmor",
    "T3-M4": "VX-3615",
    "3C-FD": "VX-4600",
    "HK-50 series assassin automaton": "Xanharhar-50 vellyrzen orlor ordraul",
    "HK-50 Series Assassin Automaton": "Lyrbel-50 Vorrendra Lorwen Keldor",
    "B1-Series Battle Automatons": "Oryornis1-Mirsol Arkeldor Morfarlor",
    "B1-Series battle automatons": "Solarvor1-Drayordor drasarsol rensol",
    "Phase I Replica Trooper Armor": "Solnarar Lorron Dorkasol Lyrar Narjor",
    "88-R Nightscreamer": "88-Lorel Galcor",
    "A95 Stingbeam": "Zendrathal95 Farlorsar",
    "Nomad Four transport": "Elnisvor Mirsarhar arthal",
    "HFY-3920 shuttle ferry": "Lorgalron-3920 vexrenka elmircor",
    "Bavos-II heavy-duty military space platform": "Yorzenka-Lyrul harel-harnaryor dradorwen narwenvel solhar",
    "Bavos-I heavy-duty military space platform": "Lyrka-Nistor morlyrtor-xanion dratorul xanrensol xanzen",
    "Altor-class supply ship": "Kelel-kael narronkel thalsol",
    "Defender-class light corvette": "Vordor-mirarquin orlor galronor",
    "TX-225 GAVw \"Occupier\"": "Torcor-225 Elwenvel \"Dravexel\"",

    # Lore items & scripts
    "Aurebesh": "Vexscript",
    "Bazeese script": "Baze script",
    "High Astral alphabet": "High Meridian alphabet",
    "Astral Basic Standard": "Meridian Basic Standard",
    "Magnate Tongue": "Magnate dialect",
    "Huttese": "Magnate tongue",
    "acthorn trees": "tarnwood trees",
    "acthorn tree": "tarnwood tree",
    "acthorn": "tarnwood",
    "Aalagar": "Elvorvex",
    "Kalkite": "Velkrite",
    "kalkite": "velkrite",
    "Stratos Distribution": "Stratos Network",
    "Morpitoo's language": "Morpivan's language",
    "Baran Do": "Lyrpraren Pralor",
    "Hidden Ones": "Veiled Keepers",
    "Flame-Wielders": "Ember Bearers",
    "Nihil marauders": "Lordraul renelka",
    "Nihil": "Arcorlor",
    "Heltraxi": "Pranar",
    "Scarlet Skulls": "Narul Wenvor",
    "Partisans": "Freeblades",
    "Partisan": "Freeblade",
    "Mortis gods": "Mornis gods",
    "sabacc": "savaq",
    "bacta": "medigel",
    "podrace": "skyrace",
    "beckon call": "summon ping",
    "Galven-pattern": "Jordra-rontortor",
    "berserker rifle": "ravager rifle",
    "Beemon package": "Veymon package",
    "auxiliary brain": "auxiliary cortex",
    "cyanogen silicate": "cyanate silicate",
    "ardanium": "ardavium",
    "accellerite": "accelerite",
    "plastoid": "plasteel",
    "microblaster": "micro-pulse weapon",

    # Meta / production (anonymize remaining franchise hooks)
    "John Williams": "Jon Whelan",
    "London Symphony Orchestra": "London Meridian Orchestra",
    "Sony Classical": "Sonic Classical",
    "Tomorrowland Terrace": "Tomorrow Terrace",
    "Disneyland Park": "Nebuland Park",
    "Phantom Menace": "Veil Menace",
    "The Phantom Menace": "The Veil Menace",
    "A New Hope": "A New Dawn",
    "Return of the Lumen": "Return of the Order",
    "Revenge of the Umbral": "Revenge of the Shadow",
    "The Veil Menace": "The Veil Threat",
    "Episode I": "Chronicle I",
    "Episode III": "Chronicle III",
    "Episode IV": "Chronicle IV",
    "Episode VI": "Chronicle VI",
    "Episode VII": "Chronicle VII",
    "Battlefront II": "Frontline II",
    "Knights of the First Concord": "Knights of the First Pact",
    "Visionaries": "Dreamwrights",
    "Automaton Tales": "Clockwork Tales",
    "Voidstream": "Nullstream",
    "AstralRift.com": "VeilRift.com",
    "Helix Studios": "Helion Studios",
    "Helix Press": "Helion Press",
    "Nebula+": "Orbital+",
    "Prism Light & Magic": "Prism Forge",
    "Dark Comet Comics": "Black Comet Comics",
    "Vorn Music": "Veyrn Music",
    "NovaForge": "Nova Foundry",
}

_noops = sorted(source for source, target in EXPANSION.items() if source == target)
if _noops:
    raise ValueError(
        "No-op mappings are not allowed in EXPANSION: "
        + ", ".join(_noops[:20])
    )
