"""Pass-2 replacements and readability fixes."""

PASS2: dict[str, str] = {
    # Meta / episodes
    "Episode VII": "Chronicle VII",
    "Episode VI": "Chronicle VI",
    "Episode IV": "Chronicle IV",
    "Episode III": "Chronicle III",
    "Episode I": "Chronicle I",
    "the Resistance": "the Vanguard",
    "Resistance returns": "Vanguard returns",
    "Resistance must": "Vanguard must",
    "Knights of the First Concord": "Knights of the First Pact",
    "The Umbral Lords": "The Shadow Lords",
    "Return of the Lumen": "Return of the Order",
    "Revenge of the Umbral": "Revenge of the Shadow",
    "In A Future, Far Beyond The Veil...": "Beyond The Outer Veil",
    "A Long Time Ago, In A Cluster Far Beyond The Veil": "Long ago, beyond the outer veil",
    "In A Future, Far Beyond The Veil …": "Beyond The Outer Veil",
    "In A Future, Far Beyond The Veil…": "Beyond The Outer Veil",
    "In A Future, Far Beyond The Veil": "Beyond The Outer Veil",
    "Bonta Eve Classic Podrace": "Bonta Eve Classic Skyrace",
    "Bonta Eve Classic podrace": "Bonta Eve Classic skyrace",
    "Podrace": "skyrace",
    "podrace": "skyrace",
    "Mos Espan Podrace": "Mos Pelan Skyrace",
    "Mos Espan": "Mos Pelan",
    "Mos Eisden": "Mos Eislor",

    # Weapons / tech leaks
    "microblaster": "micro-pulse weapon",
    "blasters": "pulse weapons",
    "blaster rifle": "pulse rifle",
    "blaster bolts": "pulse bolts",
    "blaster": "pulse weapon",
    "Galven-pattern": "Gavlen-pattern",
    "Padawans": "Acolytes",
    "Padawan": "Acolyte",
    "HK-50 Series Assassin Automaton": "HX-50 Series Assassin Automaton",
    "HK-50 series assassin automaton": "HX-50 series assassin automaton",
    "HK-50": "HX-50",
    "T3-M4": "T3-MX",
    "Solo: An Astral Rift Chronicle": "Scout: An Astral Rift Chronicle",
    "Solo: A Astral Rift Chronicle": "Scout: An Astral Rift Chronicle",
    "microblasters": "micro-pulse weapons",
    "Leviathan": "Titan",
    "_Leviathan_": "_Titan_",
    "Leviath": "Titan",
    "_Leviath_": "_Titan_",
    "Orson Krevaln": "Orson Krevan",
    "Krevaln": "Krevan",
    "Director Krevaln": "Director Krevan",
    "Hero of Tython": "Hero of Tythos",
    "RZ-1 A-wing interceptors": "RZ-1 Skyblade interceptors",
    "RZ-1 A-wing interceptor": "RZ-1 Skyblade interceptor",
    "XT-1300 light freighter": "Renlor-1300 xanzen dorwen",
    "_Altor_ -class supply ship": "Kelel-kael Narronkel Thalsol",
    "_Altor_ -class supply ships": "Kelel-kael Narronkel Thalsol units",
    "_Altor_ -class": "Kelel-kael",
    "Altor-class supply ship": "Kelel-kael Narronkel Thalsol",
    "Altor-class supply ships": "Kelel-kael Narronkel Thalsol units",
    "Altor": "Kelel",
    "Bavos-I heavy-duty military space platform": "Lyrka-Nistor Morlyrtor-xanion Dratorul Xanrensol Xanzen",
    "Bavos-II heavy-duty military space platform": "Yorzenka-Lyrul Harel-harnaryor Dradorwen Narwenvel Solhar",
    "Bavos-I military space platform": "Lyrka-Nistor military space platform",
    "Bavos-I space station": "Lyrka-Nistor space station",
    "Bavos-I": "Lyrka-Nistor",
    "Bavos-II": "Yorzenka-Lyrul",
    "HFY-3920 shuttle ferries": "Lorgalron-3920 Vexrenka Elmircor units",
    "HFY-3920 shuttle ferry": "Lorgalron-3920 Vexrenka Elmircor",
    "HFY-3920": "Lorgalron-3920",
    "A95 Stingbeams": "Zendrathal95 Farlorsars",
    "A95 Stingbeam": "Zendrathal95 Farlorsar",
    "Stingbeams": "Zendrathal95 Farlorsars",
    "Stingbeam's": "Zendrathal95 Farlorsar's",
    "Stingbeam": "Zendrathal95 Farlorsar",
    "T3-series Utility Automaton": "Tiren-series Utility Automaton",
    "T3-series utility automaton": "Tiren-series utility automaton",
    "T3-series": "Tiren-series",
    "3C-series utility automaton": "Vorn-series utility automaton",
    "3C-series": "Vorn-series",
    "3C automaton": "Vorn automaton",
    "Replica Trooper **17**": "**Tordrasar 17**",
    "Replica trooper **17**": "**Tordrasar 17**",
    "C-3PX": "C-3KX",
    "R2-K4": "R2-KX",
    "BX-8": "BX-7",
    "BB-8": "BX-7",
    "B1-Series Battle Automatons": "B1-Series War Automatons",
    "B1-Series battle automatons": "B1-Series war automatons",

    # Factions / orgs
    "Damask Holdings": "Veilmask Holdings",
    "Damask": "Veilmask",
    "Nihil marauders": "Null Concord marauders",
    "Nihil": "Null Concord",
    "Baran Do": "Baran Du",
    "Kuat Drive Yards": "Krevat Drive Yards",
    "Kuat": "Krevat",
    "Ikas-Adno": "Ikas-Adra",
    "Beemon Laborotories": "Beemon Laboratories",

    # Characters
    "Quarsh Panaka": "Quarsh Panek",
    "Mariek Panaka": "Mariek Panek",
    "Panaka": "Panek",
    "Padma Amidala": "Padma Amidal",
    "Queen Padma Amidala": "Queen Padma Amidal",
    "Senator Padma Amidala": "Senator Padma Amidal",
    "Amidala": "Amidal",
    "Luthen Rael": "Luthen Raal",
    "Dedra Meero": "Dedra Miro",
    "Major Lio Partagaz": "Major Lio Partaz",
    "Lio Partagaz": "Lio Partaz",
    "Partagaz": "Partaz",
    "Meero": "Miro",
    "Orson Krennic": "Orson Krevaln",
    "Krennic": "Krevaln",
    "Cassian Andor": "Cassian Endren",
    "Cassian Endor": "Cassian Endren",
    "Andor": "Andren",
    "Din Djarin": "Din Jarros",
    "Djarin": "Jarros",
    "Rey": "Raya",
    "Vergere": "Vergara",
    "Vrook Lamar": "Vrook Lamarr",
    "Vestara Khai": "Vestara Kai",
    "Gavar Khai": "Gavar Kai",
    "Kazuda Xiono": "Kazuda Ziono",
    "Imanuel Doza": "Imanuel Dozar",
    "Synara San": "Synara Sen",
    "Ax Tagrin": "Ax Tagren",
    "Ram Jomaram": "Ram Jomaran",
    "Vark Tarpalin": "Mornar Lorarmir",
    "Zyle Keem": "Lyryorvor Pramor",
    "Saw Gerrera": "Saw Gerron",
    "Gerrera": "Gerron",
    "Jyn Erso": "Jyn Erson",
    "Erso": "Erson",
    "Ablund": "Ronvorvor",
    "Saal": "Pravexel",
    "McCaig": "Elorfar",
    "Chapman": "Yornar",
    "Asner": "Ororthal",
    "Carano": "Farlyrfar",
    "Tagrin": "Tagren",
    "Jacen Solo": "Jace Solen",
    "Han Solo": "Han Solen",
    "Mon Mothma": "Mon Vothra",
    "General Grievous": "General Krevox",
    "Asajj Ventress": "Asajj Ventra",
    "Jango Fett": "Jango Vett",
    "Yorpraor": "Draxon",
    "Grogu": "Grovo",
    "The Child": "The Foundling",
    "Colossus": "Asterion Station",
    "_Colossus_": "_Asterion Station_",

    # Places / battles
    "Battle of Ebaq": "Battle of Ebar",
    "Battle Of Ebaq": "Battle Of Ebar",
    "Ebaq 9": "Ebar 9",
    "Yuuzhan Tide War": "Yuzhan Tide War",
    "Clakdor VII": "Clakdor Prime",
    "Tythoni Plaza": "Ionrendra Xansol",
    "Chains Worlds Theorem": "Chain Realms Theorem",
    "Veil Menace soundtrack": "Veil Threat soundtrack",
    "Veil Menace": "Veil Threat",
    "Black Spire Station": "Black Spire Outpost",
    "anti-Ghorman": "anti-Ghoran",
    "Ghorman Massacre": "Ghoran Massacre",
    "Ghorman project": "Ghoran project",
    "Ghormans": "Ghorans",

    # Species / misc
    "uvak": "uvax",
    "Magnate Tongue": "Magnate dialect",
    "Vexscript": "Ionren",
    "Xiono family": "Zion family",
    "Xiono": "Zion",
    "Human Female": "human female",
    "Human Male": "human male",
    "Human Bounty Hunter": "human bounty hunter",
    "Hanar's Archive Seal": "Kavel's Archive Seal",
    "Hanrai's library seal": "Kavel's Archive Seal",

    # Production names (fictionalize)
    "Dave Filoni": "Dale Filoni",
    "Jon Favreau": "Jon Favereau",
    "Kathleen Kennedy": "Kathryn Kennedy",
    "Bob Iger": "Nisarion Mirjor",
    "Gina Carano": "Harkacor Farlyrfar",
    "Anthony Daniels": "Anthony Danvers",
    "Alec Guinness": "Alec Guiness",
    "Brian Daley": "Ionvex Vorarxan",
    "Iain McCaig": "Elkakel Elorfar",
    "J.W. Rinzler": "Thalcorka.Quingalxan. Hardra",
    "Guillermo del Toro": "Ionharnar lorhar Vexionvex",
    "David S. Goyer": "Yorkel Solar. Kabel",
    "J.J. Abrams": "Kaxanmir.Belzen. Harmor",
    "John Williams": "Jon Whelan",
    "Jon Whelan": "Beldrathal Drawenron",
    "Christie Golden": "Lyrvexkel Fardor",
    "Caitlin Kennedy": "Vorsarjor Galjor",
    "Brian Kesinger": "Narkel Belul",
    "Ian Keltie": "Galkel Zentorul",
    "Ryder Windham": "Farulfar Corjor",
    "Sue Rostoni": "Xankelar Ionvexzen",
    "Mary Franklin": "Lyrron Mircorxan",
    "Pat Fraley": "Velion Belwenzen",
    "Kevin Burke": "Ulharxan Arsar",
    "Burke": "Arsar",
    "Randy Stradley": "Zendor Vexion",
    "Nick Chapman": "Vorfarsol Yornar",
    "Lance Priebe": "Arfarion Wenkelgal",
    "Chris Wyatt": "Belfar Belbel",
    "Wyatt": "Belbel",
    "Darragh O'Farrell": "Harbelcor Morthal",
    "Gavin Hignight": "Narbel Elwenhar",
    "Hignight": "Elwenhar",
    "Brandon Auman": "Wenion Ulprayor",
    "Auman": "Ulprayor",
    "Doza": "Dozar",
    "Aaron Boulding": "Kelthal Narpranar",
    "For other uses, see **Ed**.": "For other uses, see **Ororthal**.",
    "Ed": "Ororthal",
}

_noops = sorted(source for source, target in PASS2.items() if source == target)
if _noops:
    raise ValueError(
        "No-op mappings are not allowed in PASS2: " + ", ".join(_noops[:20])
    )
